# Generated by Django 5.0.6 on 2026-05-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='CI')),
                ('nacionalidad', models.CharField(choices=[('Boliviana', 'Boliviana'), ('Argentina', 'Argentina'), ('Brasilena', 'Brasilena'), ('Chilena', 'Chilena'), ('Peruana', 'Peruana'), ('Otra', 'Otra')], default='Boliviana', max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno'), ('Mixto', 'Mixto')], max_length=20)),
                ('jornada', models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Por Horas', 'Por Horas')], max_length=20)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turno',
            },
        ),
    ]
