# Generated by Django 5.0.6 on 2026-05-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cliente', serialize=False, to='core.persona')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('razon_social', models.CharField(blank=True, max_length=60, null=True, verbose_name='Razon Social')),
                ('tipo', models.CharField(choices=[('minorista', 'Minorista'), ('mayorista', 'Mayorista')], default='minorista', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Usuario para acceder a la tienda online', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
