# Generated by Django 5.0.6 on 2026-05-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, default='bi-tag', help_text='Clase de icono Bootstrap (ej: bi-laptop)', max_length=50)),
                ('color', models.CharField(blank=True, default='primary', help_text='Color Bootstrap: primary, success, warning, danger, info', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparicion (menor primero)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Codigo SKU')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, help_text='Precio minorista (publico)', max_digits=10)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, default=0, help_text='Precio para mayoristas (0 = mismo que minorista)', max_digits=10)),
                ('cant_min_mayorista', models.PositiveIntegerField(default=12, help_text='Cantidad minima para precio mayorista')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('destacado', models.BooleanField(default=False, help_text='Aparece en la home de la tienda')),
                ('visible_tienda', models.BooleanField(default=True, help_text='Mostrar en tienda online')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_lote', models.CharField(max_length=50, verbose_name='Nro de Lote')),
                ('cantidad_recibida', models.PositiveIntegerField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('fecha_adquision', models.DateField(verbose_name='Fecha de adquisicion')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('coste_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coste_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='compras.detallecompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Inventario (Lote)',
                'verbose_name_plural': 'Inventario (Lotes)',
                'db_table': 'inventario',
                'ordering': ['fecha_adquision'],
            },
        ),
    ]
