# Generated by Django 5.0.6 on 2026-04-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('representante_legal', models.CharField(max_length=100)),
                ('pais', models.CharField(choices=[('Bolivia', 'Bolivia'), ('China', 'China'), ('Brasil', 'Brasil'), ('Argentina', 'Argentina'), ('Estados Unidos', 'Estados Unidos'), ('Espana', 'Espana'), ('Mexico', 'Mexico'), ('Otro', 'Otro')], default='Bolivia', max_length=50)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['empresa'],
            },
        ),
    ]
