# Generated by Django 5.0.6 on 2026-05-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Ej: Casa, Oficina', max_length=50)),
                ('ciudad', models.CharField(default='Santa Cruz', max_length=50)),
                ('zona', models.CharField(max_length=80)),
                ('calle', models.CharField(max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('referencia', models.TextField(blank=True, help_text='Referencias para encontrar el lugar')),
                ('telefono', models.CharField(max_length=20)),
                ('es_principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'tienda_direccion',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pago reportado'), ('confirmado', 'Confirmado por TUMOMITO'), ('preparando', 'Preparando envio'), ('enviado', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('qr', 'QR / Tigo Money'), ('contra_entrega', 'Pago contra entrega')], max_length=20)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('referencia_pago', models.CharField(blank=True, max_length=100)),
                ('monto_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tienda.direccion')),
                ('nota_venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origen', to='ventas.notaventa')),
            ],
            options={
                'verbose_name': 'Pedido Online',
                'verbose_name_plural': 'Pedidos Online',
                'db_table': 'tienda_pedido',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_mayorista', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'tienda_detalle_pedido',
            },
        ),
    ]
