# Generated by Django 5.0.6 on 2026-05-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.SlugField(help_text='Identificador unico (ej: vendedor, cajero)', max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('modulos', models.JSONField(default=list, help_text='Lista de codigos de modulos accesibles')),
                ('es_admin', models.BooleanField(default=False, help_text='Si es True, tiene acceso a todo')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='empleado', serialize=False, to='core.persona')),
                ('telf_contacto', models.CharField(max_length=20, verbose_name='Telefono de contacto')),
                ('nombre_contacto', models.CharField(max_length=60, verbose_name='Nombre de contacto')),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero/a'), ('Casado', 'Casado/a'), ('Divorciado', 'Divorciado/a'), ('Viudo', 'Viudo/a')], default='Soltero', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Usuario para acceder al sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_perfil', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='personal.rol')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_laboral', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Plazo Fijo', 'Plazo Fijo'), ('Por Obra', 'Por Obra'), ('Practicas', 'Practicas')], max_length=40)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turno')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_log', models.CharField(max_length=20, verbose_name='Nombre de usuario')),
                ('passwordlog', models.CharField(max_length=255)),
                ('email_rec', models.EmailField(max_length=254, verbose_name='Email de recuperacion')),
                ('fechalog', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Logins',
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='personal.login')),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
                'db_table': 'bitacora',
                'ordering': ['-fecha'],
            },
        ),
    ]
