# Generated by Django 5.0.6 on 2026-04-29 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(choices=[('BOB', 'Boliviano'), ('USD', 'Dolar Americano')], default='BOB', max_length=10)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.empleado')),
            ],
            options={
                'verbose_name': 'Nota de Venta',
                'verbose_name_plural': 'Notas de Venta',
                'db_table': 'nota_venta',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(blank=True, max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.inventario')),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.notaventa')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalle_venta',
            },
        ),
    ]
